---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cfxhsigb/public_html # Add /<app_folder> if required
    - /bin/cp index.html $DEPLOYPATH #Copy specific file to destination from root
    - /bin/cp robots.txt $DEPLOYPATH #copy specific file from source sub folder
    - /bin cp /assets/* $DEPLOYPATH #copy all from sub folder root
